variables:
  projectDirectory: 'formbot_app'

trigger:
- master

jobs:
  - job: Android
    pool: 
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'latest'