name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  projectDirectory: 'formbot_app'

trigger:
- master

jobs:
  - job: Flutter
    pool: 
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'latest'
      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)
