# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  FlutterChannel: 'stable'
  FlutterVersion: 'latest'

  ProjectDirectory: '$(Build.SourcesDirectory)'
  BuildNumber: '$(Build.BuildNumber)'
  BuildMessage: '$(Build.SourceVersionMessage)'
  BuildDirectory: '$(ProjectDirectory)/build/app/outputs/apk/release/app-release.apk'

jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        displayName: Setup Flutter
        inputs:
          channel: '$(FlutterChannel)'
          version: '$(FlutterVersion)'
      - task: PowerShell@2
        displayName: Setup environment
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"
