name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  projectDirectory: 'formbot_app'

trigger:
- master

jobs:
  - job: Flutter
    pool: 
      vmImage: 'macOS-latest'
    steps:
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'credentials.json'
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'google-services.json'
      - task: CopyFiles@2
        displayName: 'Secured Copy Credentials JSON'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: '*.json'
          TargetFolder: '$(System.DefaultWorkingDirectory)/formbot_app/assets'
      - task: CopyFiles@2
        displayName: 'Secured Copy Google Service JSON'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: '*.json'
          TargetFolder: '$(System.DefaultWorkingDirectory)/formbot_app/android/app'
      - task: FlutterInstall@0
        displayName: 'Install Flutter Tools'
        inputs:
          channel: 'stable'
          version: 'latest'
      - task: FlutterBuild@0
        displayName: 'Build Flutter'
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)
# commenting out test task until unit tests are developed
#      - task: FlutterTest@0
#        displayName: 'Unit Test Flutter'
#        inputs:
#         projectDirectory: $(projectDirectory)
      - task: CopyFiles@2
        displayName: 'Copy Artifiacts'
        inputs:
          Contents: '**/*.apk'
          TargetFolder: '$(build.artifactStagingDirectory)'
        condition: succeededOrFailed()
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
        condition: succeededOrFailed()