name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  projectDirectory: 'formbot_app'

trigger:
- master

jobs:
  - job: Flutter
    pool: 
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'latest'
      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)
      - task: FlutterTest@0
        inputs:
         projectDirectory: $(projectDirectory)
      - task: CopyFiles@2
        inputs:
          Contents: '**/*.apk'
          TargetFolder: '$(build.artifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
