variables:
  projectDirectory: 'formbot_app'

trigger:
- master

jobs:
  - job: Android
    pool: 
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'custom'
          customVersion: '1.17.5'
      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)
